[package]
name = "shipper-release"
edition = "2021"
description = "Release orchestrator and changelog management program for shipper"
license-file = "../LICENSE"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
clap = { version = "4.3.10", features = ["derive"] }
git2 = "0.18.3"
regex = "1.8.4"
semver = "1.0.17"
