name: Bug Report
description: Report a problem with shipper
title: "bug: "
labels: ["bug"]
assignees:
  - ericswpark
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: target-platform
    attributes:
      label: "What subsystem are you reporting a problem with? (Hint: you can select multiple!)"
      multiple: true
      options:
        - shipper (backend)
        - shipper (webUI)
        - shipper (API)
        - shippy
        - Docker images
        - Release helper
        - N/A (don't select anything above)
  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Function X does Y instead of Z...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: What can we do to reproduce the problem?
      description: |
        If your bug only occurs randomly, please type "sporadic" into this box.
        If this box is empty for no reason your bug report may be closed.
      placeholder: |
        1. Navigated to page "/maintainers/"...
        2. Clicked on button "X"...
        3. Scrolled to the end of the page...
        4. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell 
  - type: textarea
    id: shipper-version
    attributes:
      label: shipper version
      description: What version of shipper are you running?
      placeholder: master or specific version string (such as 2.18.0) or N/A
    validations:
      required: true
  - type: textarea
    id: shippy-version
    attributes:
      label: shippy version
      description: What version of shippy are you running?
      placeholder: master or specific version string (such as 2.18.0) or N/A
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Anything else?
      description: |
        Links, references, screenshots, etc.
        Anything that you think would help resolve this bug. 