site_name: shipper documentation

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
  language: en

nav:
    - Home: 'index.md'
    - 'For sysadmins':
        - 'Configuration': 'sysadmin/Configuration.md'
        - 'Customization': 'sysadmin/Customization.md'
        - 'Installation': 'sysadmin/Installation.md'
        - 'Upgrading': 'sysadmin/Upgrading.md'
        - 'Administration': 'sysadmin/Administration.md'
        - 'FAQ': 'sysadmin/FAQ.md'
        - 'Troubleshooting': 'sysadmin/Troubleshooting.md'
    - 'For developers':
        - 'Development': 'developer/Development.md'
        - 'Translation': 'developer/Translation.md'
        - 'API': 'developer/API.md'

extra:
  version:
    provider: mike

plugins:
  - mike:
      version_selector: true

markdown_extensions:
    - toc:
        permalink: "#"
    - admonition
    - pymdownx.details
    - pymdownx.superfences
