name: Django Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    env:
      SHIPPER_SECRET_KEY: "duk4hvedu3zxnmw@shnjw7z^)x#wcm@cj05t5f&#90rx-g44d2"
      SHIPPER_DEBUG: 1
      SHIPPER_ALLOWED_HOSTS: "localhost 127.0.0.1"
      SHIPPER_MAIN_WEBSITE_URL: "https://example.com"
      SHIPPER_DOWNLOADS_PAGE_MAIN_BRANDING: "User Downloads"
      SHIPPER_DOWNLOADS_PAGE_DONATION_URL: "https://paypal.com/test"
      SHIPPER_SENTRY_SDK_DSN: "https://34fd99861ec84ad2bd731c50267dc5f6@o444286.ingest.sentry.io/5418995"
      SHIPPER_SENTRY_SDK_PII: False

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Install coverage
      run: |
        pip install coverage
    - name: Generate coverage report
      run: |
        coverage run --source='.' manage.py test
    - name: Upload coverage report
      uses: codecov/codecov-action@v2.0.1
      with:
        verbose: true
        fail_ci_if_error: true