name: Send event on manual invocation

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version'
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SHIPPER_DOCKER_REPO_ACCESS_TOKEN }}
          repository: shipperstack/shipper-docker
          event-type: backend-release-event
          client-payload: '{"tag_version": "${{ github.event.inputs.tag_version }}"}'
