name: Send event on release creation

on:
  push:
    tags:
      - '*.*.*'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag version
        run: echo "TAG_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SHIPPER_DOCKER_REPO_ACCESS_TOKEN }}
          repository: shipperstack/shipper-docker
          event-type: backend-release-event
          client-payload: '{"tag_version": "${{ env.TAG_VERSION }}"}'